model = "gpt-5.1-codex-max"
model_reasoning_effort = "xhigh"
network_access = true

[tools]
web_search = true

[projects."/var/www/local.its.wp-test/htdocs/shop"]
trust_level = "trusted"

[projects."/home/dev_local/dotfiles"]
trust_level = "trusted"

[projects."/var/www/local.its.wp-test/htdocs/business"]
trust_level = "trusted"

[projects."/var/www/local.its.wp-test/htdocs/band"]
trust_level = "trusted"

[projects."/var/projects/net.itsj-draft.test"]
trust_level = "trusted"

[projects."/var/projects/net.itsj-draft.t2f-cmp"]
trust_level = "trusted"

[projects."/var/www/local.its.wp-test/htdocs/legal"]
trust_level = "trusted"

[projects."/var/www/local.its.its-subsc/laravel"]
trust_level = "trusted"

[projects."/var/projects/net.itsj-draft.its-subsc"]
trust_level = "trusted"

[projects."/var/www/local.its.wp-test/htdocs/band/wp-content/themes/bp_wp_site"]
trust_level = "trusted"

[projects."/var/projects/net.itsj-draft.ibv3"]
trust_level = "trusted"

[projects."/var/www/local.its.wp-test/htdocs/ren-s"]
trust_level = "trusted"

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.google_spreadsheets]
command = "npx"
args = ["-y", "google-spreadsheets-mcp-server"]

[mcp_servers.playwright]
command = "npx"
args = ["-y", "playwright-mcp-server"]

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
