model = "gpt-5.2-codex"
model_reasoning_effort = "high"
network_access = true

[tools]
web_search = true

[projects."/var/www/local.its.wp-test/htdocs/shop"]
trust_level = "trusted"

[projects."/home/dev_local/dotfiles"]
trust_level = "trusted"

[projects."/var/www/local.its.wp-test/htdocs/business"]
trust_level = "trusted"

[projects."/var/www/local.its.wp-test/htdocs/band"]
trust_level = "trusted"

[projects."/var/projects/net.itsj-draft.test"]
trust_level = "trusted"

[projects."/var/projects/net.itsj-draft.t2f-cmp"]
trust_level = "trusted"

[projects."/var/www/local.its.wp-test/htdocs/legal"]
trust_level = "trusted"

[projects."/var/www/local.its.its-subsc/laravel"]
trust_level = "trusted"

[projects."/var/projects/net.itsj-draft.its-subsc"]
trust_level = "trusted"

[projects."/var/www/local.its.wp-test/htdocs/band/wp-content/themes/bp_wp_site"]
trust_level = "trusted"

[projects."/var/projects/net.itsj-draft.ibv3"]
trust_level = "trusted"

[projects."/var/www/local.its.wp-test/htdocs/ren-s"]
trust_level = "trusted"

[projects."/var/projects/net.itsj-draft.isv6"]
trust_level = "trusted"

[projects."/home/dev_local/mine/SAMS"]
trust_level = "trusted"

[projects."/home/dev_local/dev_plugin/codex.nvim"]
trust_level = "trusted"
